package com.university.authservice.persistence.entity;

public enum RoleEnum {
    ADMIN_USERS, // CREATE_USER, READ_USER, UPDATE_USER, DELETE_USER, DISABLE_USER, ENABLE_USER.
    ADMIN_ACTIVITIES, // CREATE_ACTIVITY, READ_ACTIVITY, UPDATE_ACTIVITY, DELETE_ACTIVITY, DISABLE_ACTIVITY, ENABLE_ACTIVITY.
    STUDENT // READ_ACTIVITY, ENROLL_ACTIVITY, UNENROLL_ACTIVITY.
}
